oidc:
  issuer-uri: https://boahey-dev-443565.okta.com/oauth2/default
  client-id: 0oa52dpdqvDdqlKbn4x6
  client-secret: jyBrIujn7vuDdQUofvgRHvf0da_wZfRcqlvMMIh7

spring:
  security:
    oauth2:
      client:
        provider:
          okta:
            issuer-uri: ${oidc.issuer-uri}
        registration:
          okta:
            client-id: ${oidc.client-id}
            client-secret: ${oidc.client-secret}
      resourceserver:
        jwt:
          issuer-uri: ${oidc.issuer-uri}
